-- ════════════════════════════════════════════════════════════════════
-- SAHA PAKETİ (2026-08-07) — Supabase SQL Editor'de BİR KEZ Run (idempotent).
--
-- Likidite fazının 5 sunucu sözleşmesi. Hepsi tek dosyada, sırayla:
--
--   1) profiles.available_until   — "Aracım bugün müsait" anahtarı ARTIK KALICI.
--                                   Ana sayfadaki düğme şimdiye kadar sadece
--                                   useState idi: sayfa yenilenince sıfırlanıyor,
--                                   panelde hiç görünmüyordu. Admin "Eşleştir"
--                                   sekmesi bunu okuyup arama sırasını kurar.
--   2) search_signals             — SONUÇSUZ ARAMA kaydı (talep sinyali).
--                                   "Bergama · mıcır · 14 arama · 0 ilan" →
--                                   hangi ocağa gidileceğini liste söyler.
--                                   Geriye dönük TOPLANAMAYAN veri.
--   3) (SQL yok)                  — WhatsApp paylaşımı tamamen istemci tarafı.
--   4) listings.recurring_*       — DÜZENLİ SEVKİYAT gerçekten tekrarlanır:
--      + run_my_recurrences()       sırası gelen düzenli iş otomatik yeniden
--      + accept_job guard'ı         açılır ve ÖNCEKİ NAKLİYECİYE 12 saat
--                                   öncelik tanınır (switching cost).
--   5) profiles.invite_code/      — DAVET / REFERANS: kim kimi getirdi.
--      invited_by + 3 RPC
--
-- ÖN KOŞUL: schema.sql + migration-2026-07-saha-crm2.sql + profil-gizlilik
--           + tasima-turu-uyum çalışmış olmalı (accept_job burada onun
--           üzerine yazılır — tüm eski guard'ları KORUYARAK).
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
-- 1) MÜSAİTLİK — profiles.available_until
-- ════════════════════════════════════════════════════════════════════
-- Damga GELECEKTE ise nakliyeci "şu an müsait" sayılır. İstemci bunu
-- günün sonuna (23:59) yazar; ertesi gün kendiliğinden düşer — böylece
-- "açık unutulmuş müsaitlik" diye yanlış bir sinyal oluşmaz.
alter table public.profiles add column if not exists available_until timestamptz;
create index if not exists profiles_available_idx
  on public.profiles (available_until desc nulls last);

-- RLS notu: yazma zaten profiles_update (auth.uid() = id) ile serbest;
-- guard_profile_update yalnız verified/status/role'ü kilitler, bu kolona
-- dokunmaz. Okuma profiles_read (üye) + profiles_admin_all ile gelir.
-- profiles_public görünümüne BİLEREK eklenmedi: kayıtsız ziyaretçinin
-- "hangi nakliyeci bugün boşta" listesini toplaması gerekmiyor.


-- ════════════════════════════════════════════════════════════════════
-- 2) TALEP SİNYALİ — search_signals
-- ════════════════════════════════════════════════════════════════════
-- Aradı ama BULAMADI kaydı. Kayıtsız ziyaretçi de yazabilir (user_id null),
-- çünkü asıl değerli sinyal çoğu zaman henüz üye olmamış alıcıdan gelir.
-- Okuma YALNIZ admin.
create table if not exists public.search_signals (
  id           bigint generated by default as identity primary key,
  user_id      uuid references public.profiles(id) on delete set null,
  role         text not null default '',
  type         text not null default '',   -- is | arac | urun | all
  cat          text not null default '',   -- hafriyat | silobas | all
  q            text not null default '',   -- serbest metin arama
  material     text not null default '',
  il           text not null default '',
  result_count int  not null default 0,    -- 0 = hiç sonuç yok (asıl sinyal)
  created_at   timestamptz not null default now(),
  -- Sunucu tarafı sınır: istemci kırılsa/kötüye kullanılsa bile tablo şişmesin.
  constraint search_signals_q_len check (char_length(q) <= 120)
);
create index if not exists search_signals_created_idx on public.search_signals (created_at desc);

alter table public.search_signals enable row level security;
drop policy if exists search_signals_insert     on public.search_signals;
drop policy if exists search_signals_admin_read on public.search_signals;
-- Yazma: herkes, ama başkasının kimliğiyle DEĞİL (user_id null ya da kendisi).
create policy search_signals_insert on public.search_signals
  for insert with check (user_id is null or auth.uid() = user_id);
create policy search_signals_admin_read on public.search_signals
  for select using (public.is_admin());
grant insert on public.search_signals to anon, authenticated;
grant select on public.search_signals to authenticated;
-- NOT: identity kolonunun dizisi için ayrı sequence grant'ı GEREKMEZ
-- (kimlik dizisi kolona bağlıdır, INSERT hakkı yeter). Şemaya toptan
-- "grant usage on all sequences" vermek gereksiz geniş olurdu.


-- ════════════════════════════════════════════════════════════════════
-- 4) DÜZENLİ SEVKİYAT — tekrar + önceki nakliyeciye öncelik
-- ════════════════════════════════════════════════════════════════════
-- Bugüne kadar `recurring` yalnızca bir ETİKETTİ: ilan kartında "↻ DÜZENLİ"
-- yazıyor, hiçbir şey üretmiyordu. Formda toplanan sıklık/süre/günde-sefer
-- alanları DB'ye hiç yazılmıyordu (listingToRow'da yoktular).
alter table public.listings add column if not exists recurring_freq     text;    -- gunluk | haftalik | aylik
alter table public.listings add column if not exists recurring_duration text;
alter table public.listings add column if not exists daily_trips        int;
-- Şablon ilan: sıradaki seferin ne zaman açılacağı.
alter table public.listings add column if not exists next_run_at        timestamptz;
-- Kopya ilan: hangi şablondan doğdu.
alter table public.listings add column if not exists parent_id          bigint;
-- Öncelik penceresi: bu süre dolana kadar işi YALNIZ bu nakliyeci kabul edebilir.
alter table public.listings add column if not exists reserved_for_id    uuid;
alter table public.listings add column if not exists reserved_until     timestamptz;
create index if not exists listings_next_run_idx on public.listings (next_run_at) where next_run_at is not null;
create index if not exists listings_parent_idx   on public.listings (parent_id)   where parent_id is not null;

-- Sıklık → interval. Bilinmeyen değer haftalık sayılır.
create or replace function public.recurrence_interval(p_freq text)
returns interval language sql immutable as $$
  select case lower(coalesce(p_freq,''))
           when 'gunluk' then interval '1 day'
           when 'aylik'  then interval '1 month'
           else               interval '7 days'
         end;
$$;

-- Düzenli ilan oluşturulunca / işaretlenince sıradaki seferin saatini kur.
-- İstemcide hesaplamak yerine trigger: admin "adına ilan" akışı ve ileride
-- eklenecek her yol otomatik doğru olur. recurring kaldırılırsa sıra silinir
-- (= üyenin "tekrarı durdur" düğmesi tam olarak bu).
create or replace function public.set_next_run()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.recurring is true then
    -- Kopya ilanlar (parent_id dolu) ŞABLON DEĞİLDİR; onlara sıra kurulmaz.
    if new.parent_id is null and new.next_run_at is null then
      new.next_run_at := now() + public.recurrence_interval(new.recurring_freq);
    end if;
  else
    new.next_run_at := null;
  end if;
  return new;
end; $$;
drop trigger if exists listings_set_next_run on public.listings;
create trigger listings_set_next_run
  before insert or update of recurring, recurring_freq on public.listings
  for each row execute function public.set_next_run();

-- ── Çekirdek: bir şablonun sırası geldiyse yeni seferi aç ──────────
-- p_owner null ise TÜM sahiplerin şablonları taranır (yalnız admin çağırır).
-- Döner: açılan yeni ilan sayısı.
--
-- KURALLAR (hepsi bilinçli):
--  • Şablon = recurring + next_run_at dolu ilan. Kopya İLAN ŞABLON DEĞİLDİR
--    (recurring=false, parent_id dolu) — yoksa üstel çoğalma olurdu.
--  • DURDURMA = recurring'i false yapmak (İlanlarım'daki düğme). Şablonun
--    'kapali'/'eslesti' olması tekrarı DURDURMAZ: "her salı 3 tır" işinin
--    şablonu zaten her hafta eşleşip kapanır — durum'a bakmak özelliği
--    ilk sefer sonrası sessizce öldürürdü.
--  • Şablonun kendisi ya da ondan doğmuş bir kopya HÂLÂ AÇIK (aktif) ise
--    yeni sefer AÇILMAZ; sıra yine ilerletilir. Geçen haftaki iş kamyon
--    bulamadıysa panoya bir tane daha atmak panoyu çöplendirir.
--  • Öncelik: önceki seferi kabul eden nakliyeci varsa yeni ilan 12 saat
--    ona ayrılır (accept_job bunu uygular). Süre dolunca herkese açılır.
--  • Sıra ilerletme ile kopyalama AYNI transaction'da; skip locked ile iki
--    eşzamanlı çağrı aynı seferi iki kez açamaz.
create or replace function public.run_recurrences(p_owner uuid)
returns int language plpgsql security definer set search_path = public as $$
declare
  t         public.listings;
  v_iv      interval;
  v_acik    boolean;
  v_prev    uuid;
  v_next    timestamptz;
  v_count   int := 0;
begin
  for t in
    select * from public.listings
     where recurring is true
       and parent_id is null
       and next_run_at is not null
       and next_run_at <= now()
       and (p_owner is null or owner_id = p_owner)
     for update skip locked
  loop
    v_iv := public.recurrence_interval(t.recurring_freq);

    -- Sırayı HER durumda ilerlet (atlanan sefer birikmesin). Geçmişte
    -- kalmış birden çok periyot varsa tek adımda bugünden SONRAKİ ilk
    -- sefere atla (min: sonraki, max olsaydı seriyi sonuna taşırdı).
    select min(x) into v_next
      from generate_series(t.next_run_at, now() + v_iv, v_iv) g(x)
     where x > now();
    update public.listings
       set next_run_at = coalesce(v_next, now() + v_iv)
     where id = t.id;

    -- Şablonun kendisi ya da bir kopyası hâlâ açık mı?
    v_acik := (t.status = 'aktif') or exists (
      select 1 from public.listings c
       where c.parent_id = t.id and c.status = 'aktif'
    );
    if v_acik then
      continue;   -- önceki sefer daha kapanmadı: yenisini açma
    end if;

    -- Önceki seferi kim aldıysa ona öncelik (en yeni kopya, yoksa şablonun kendisi).
    select c.accepted_by_id into v_prev
      from public.listings c
     where c.parent_id = t.id and c.accepted_by_id is not null
     order by c.created_at desc limit 1;
    if v_prev is null then v_prev := t.accepted_by_id; end if;

    insert into public.listings (
      type, cat, title, il, ilce, varis_il, yukleme, bosaltma, material, amount, unit,
      date_text, recurring, recurring_text, recurring_freq, recurring_duration, daily_trips,
      vehicle, capacity, price_type, price, description, km, pickup, dropoff,
      owner_id, owner_name, owner_logo, owner_verified, owner_rating,
      status, created_text, parent_id, reserved_for_id, reserved_until
    )
    select
      t.type, t.cat, t.title, t.il, t.ilce, t.varis_il, t.yukleme, t.bosaltma, t.material, t.amount, t.unit,
      t.date_text, false, t.recurring_text, t.recurring_freq, t.recurring_duration, t.daily_trips,
      t.vehicle, t.capacity, t.price_type, t.price, t.description, t.km, t.pickup, t.dropoff,
      t.owner_id, t.owner_name, t.owner_logo, t.owner_verified, t.owner_rating,
      'aktif', 'az once', t.id, v_prev,
      case when v_prev is null then null else now() + interval '12 hours' end;

    v_count := v_count + 1;
  end loop;
  return v_count;
end; $$;
revoke all on function public.run_recurrences(uuid) from public, anon, authenticated;

-- Üye kendi düzenli işlerini işletir (uygulama açılışında bir kez çağrılır).
create or replace function public.run_my_recurrences()
returns int language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then return 0; end if;
  return public.run_recurrences(auth.uid());
end; $$;
revoke all on function public.run_my_recurrences() from public, anon;
grant execute on function public.run_my_recurrences() to authenticated;

-- Admin tümünü işletir (üye uygulamayı hiç açmasa da sefer açılsın —
-- saha turunda panelden tek dokunuş).
create or replace function public.run_all_recurrences()
returns int language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Yetki yok.'; end if;
  return public.run_recurrences(null);
end; $$;
revoke all on function public.run_all_recurrences() from public, anon;
grant execute on function public.run_all_recurrences() to authenticated;

-- ── accept_job: ÖNCELİK PENCERESİ guard'ı ─────────────────────────
-- tasima-turu-uyum.sql'deki sürümün BİREBİR üstüne yazılır; oradaki tüm
-- guard'lar (ban / sahipsiz / kendi ilanı / tür / sabit fiyat / durum /
-- taşıma türü) korunur, sonuna öncelik kontrolü eklenir.
create or replace function public.accept_job(
  p_listing_id bigint, p_price numeric default null, p_vehicle jsonb default null
) returns public.listings language plpgsql security definer set search_path = public as $$
declare
  v_uid uuid := auth.uid(); v_listing public.listings; v_name text; v_status text; v_turu text;
begin
  if v_uid is null then raise exception 'Giriş gerekli.'; end if;
  select coalesce(name,''), coalesce(status,'aktif'), coalesce(tasima_turu,'')
    into v_name, v_status, v_turu
    from public.profiles where id = v_uid;
  if v_status = 'banli' then raise exception 'Hesabın askıya alındı.'; end if;
  select * into v_listing from public.listings where id = p_listing_id for update;
  if not found then raise exception 'İlan bulunamadı.'; end if;
  if v_listing.owner_id is null then raise exception 'Bu bir tanıtım ilanıdır — kabul edilemez.'; end if;
  if v_listing.owner_id = v_uid then raise exception 'Kendi ilanını kabul edemezsin.'; end if;
  if v_listing.type not in ('is','arac') then raise exception 'Bu ilan doğrudan kabul edilemez.'; end if;
  if coalesce(v_listing.price_type,'') <> 'sabit' then raise exception 'Yalnızca sabit fiyatlı ilanlar doğrudan kabul edilir.'; end if;
  if v_listing.status <> 'aktif' then raise exception 'Bu ilan artık uygun değil.'; end if;
  if v_listing.type = 'is' and (
       (v_turu = 'Hafriyat (damperli)' and v_listing.cat = 'silobas')
    or (v_turu = 'Silobas / dökme'     and v_listing.cat = 'hafriyat')
  ) then raise exception 'Bu iş taşıma türüne uygun değil — profilindeki taşıma türünü kontrol et.'; end if;
  -- YENİ: düzenli işin öncelik penceresi. Süre dolana kadar yalnız önceki
  -- seferi taşıyan nakliyeci kabul edebilir; sonra ilan herkese açılır.
  if v_listing.reserved_for_id is not null
     and v_listing.reserved_until is not null
     and v_listing.reserved_until > now()
     and v_listing.reserved_for_id <> v_uid then
    raise exception 'Bu düzenli iş şu an önceki nakliyecisine ayrılmış. % sonra herkese açılacak.',
      to_char(v_listing.reserved_until, 'DD.MM HH24:MI');
  end if;
  insert into public.offers (listing_id, from_user_id, from_user_name, price, message, status, kind)
  values (p_listing_id, v_uid, v_name, v_listing.price, 'İş sabit fiyattan kabul edildi.', 'kabul', 'direkt');
  update public.listings set status = 'eslesti', accepted_by_id = v_uid, assigned_vehicle = p_vehicle
   where id = p_listing_id returning * into v_listing;
  return v_listing;
end; $$;
grant execute on function public.accept_job(bigint, numeric, jsonb) to authenticated;


-- ════════════════════════════════════════════════════════════════════
-- 5) DAVET / REFERANS — kim kimi getirdi
-- ════════════════════════════════════════════════════════════════════
alter table public.profiles add column if not exists invite_code text;
alter table public.profiles add column if not exists invited_by  uuid references public.profiles(id) on delete set null;
create unique index if not exists profiles_invite_code_uidx
  on public.profiles (upper(invite_code)) where invite_code is not null;
create index if not exists profiles_invited_by_idx on public.profiles (invited_by) where invited_by is not null;

-- Karışması kolay harf/rakam YOK (0/O, 1/I/L). Kod telefonda okunacak.
create or replace function public.gen_invite_code()
returns text language sql volatile as $$
  select string_agg(substr('ABCDEFGHJKMNPQRSTUVWXYZ23456789',
                           (floor(random()*31)::int)+1, 1), '')
    from generate_series(1,6);
$$;

-- Kendi davet kodum (yoksa üretir). Kısa ve tekrar çağrılabilir.
create or replace function public.my_invite_code()
returns text language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); v_code text; i int := 0;
begin
  if me is null then raise exception 'Giriş gerekli.'; end if;
  select invite_code into v_code from public.profiles where id = me;
  if v_code is not null and v_code <> '' then return v_code; end if;
  loop
    i := i + 1;
    v_code := public.gen_invite_code();
    begin
      update public.profiles set invite_code = v_code where id = me;
      return v_code;
    exception when unique_violation then
      if i > 8 then raise exception 'Davet kodu üretilemedi, tekrar dene.'; end if;
    end;
  end loop;
end; $$;
revoke all on function public.my_invite_code() from public, anon;
grant execute on function public.my_invite_code() to authenticated;

-- Davet kodunu sahiplen. YALNIZ bir kez (invited_by boşken) yazılır;
-- kendi kodunu kullanmak ve 30 günden eski hesaba geriye dönük atıf yok.
-- Döner: true = atıf yazıldı.
create or replace function public.claim_invite(p_code text)
returns boolean language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid(); v_owner uuid; v_mine uuid; v_created timestamptz;
begin
  if me is null or coalesce(p_code,'') = '' then return false; end if;
  select invited_by, created_at into v_mine, v_created from public.profiles where id = me;
  if v_mine is not null then return false; end if;
  if v_created is not null and v_created < now() - interval '30 days' then return false; end if;
  select id into v_owner from public.profiles
   where invite_code is not null and upper(invite_code) = upper(trim(p_code));
  if v_owner is null or v_owner = me then return false; end if;
  update public.profiles set invited_by = v_owner where id = me and invited_by is null;
  return found;
end; $$;
revoke all on function public.claim_invite(text) from public, anon;
grant execute on function public.claim_invite(text) to authenticated;

-- Kaç kişiyi getirdim? (Üye başkasının satırını okuyamaz; sayıyı RPC verir.)
create or replace function public.my_invite_count()
returns int language sql security definer set search_path = public as $$
  select count(*)::int from public.profiles where invited_by = auth.uid();
$$;
revoke all on function public.my_invite_count() from public, anon;
grant execute on function public.my_invite_count() to authenticated;


-- ════════════════════════════════════════════════════════════════════
-- KONTROL — hepsi tek tek doğrulanabilir olmalı
-- ════════════════════════════════════════════════════════════════════
-- 1) müsaitlik kolonu (1 satır):
select column_name from information_schema.columns
 where table_schema='public' and table_name='profiles' and column_name='available_until';
-- 2) talep sinyali tablosu + 2 politika:
select relname, relrowsecurity from pg_class where relname='search_signals';
select policyname from pg_policies where tablename='search_signals' order by policyname;
-- 4) düzenli sevkiyat kolonları (7 satır):
select column_name from information_schema.columns
 where table_schema='public' and table_name='listings'
   and column_name in ('recurring_freq','recurring_duration','daily_trips',
                       'next_run_at','parent_id','reserved_for_id','reserved_until')
 order by column_name;
-- 4a) sıra kuran trigger (1 satır):
select tgname from pg_trigger where tgname = 'listings_set_next_run';
-- 4b) accept_job HEM taşıma türü HEM öncelik guard'ını taşıyor mu? (ikisi de true)
select prosrc like '%taşıma türüne uygun değil%' as turu_guard_var,
       prosrc like '%önceki nakliyecisine ayrılmış%' as oncelik_guard_var
  from pg_proc join pg_namespace n on n.oid=pronamespace
 where n.nspname='public' and proname='accept_job';
-- 5) davet kolonları + RPC'ler (3 satır: claim_invite, my_invite_code, my_invite_count):
select column_name from information_schema.columns
 where table_schema='public' and table_name='profiles'
   and column_name in ('invite_code','invited_by') order by column_name;
select proname from pg_proc join pg_namespace n on n.oid=pronamespace
 where n.nspname='public'
   and proname in ('claim_invite','my_invite_code','my_invite_count',
                   'run_my_recurrences','run_all_recurrences','run_recurrences')
 order by proname;
