-- ════════════════════════════════════════════════════════════════════
-- SAHA ADAY KAYDI (2026-08-08) — Supabase SQL Editor'de BİR KEZ Run (idempotent).
--
-- SORUN: Saha turunda ocakçıyla görüşüp bilgilerini sisteme girmenin YOLU YOKTU.
--   profiles.id → auth.users(id) FK olduğu için hesapsız profil açılamıyor;
--   panelin "Adına ilan ver" akışı hedef üyenin ÖNCEDEN kayıtlı olmasını şart
--   koşuyor. Oysa SAHA-PLANI.md §3 ve OCAK-LISTESI.md tam tersini söylüyor:
--   "vitrin taslağı ziyaretten ÖNCE hazırlanır, firma 'evet' deyince canlıya alınır".
--   Plan kâğıtta vardı, aracı yoktu.
--
-- MODEL: Önce değer, sonra hesap.
--   1) Admin bir ADAY KAYIT açar (firma adı, rol, il, malzeme…) — auth hesabı YOK.
--   2) Adayın vitrin ilanları owner_id NULL + prospect_id dolu olarak açılır.
--      İletişim firmanın kendi numarası DEĞİL, YÜKLET saha hattıdır; kabul edilemez
--      (accept_job sahipsiz ilanı zaten reddediyor — bilinçli olarak korunur).
--   3) Firma değeri görünce davet linkiyle (?firma=TOKEN) kendi hesabını açar;
--      claim_prospect aday kaydı + ilanları O HESABA devreder.
--   Şifre hiç saha ekibinden geçmez, firmanın kişisel numarası hiç yayınlanmaz.
--
-- İÇİNDEKİLER
--   1) prospects tablosu (+ RIZA KAPISI: rıza damgası yoksa yayına çıkamaz)
--   2) listings.prospect_id
--   3) guard_driver_listing_update — SAHİPLENME istisnası (BLOKER olurdu)
--   4) publish_prospect / unpublish_prospect  (admin)
--   5) prospect_by_token (anon) / claim_prospect (üye)
--
-- ÖN KOŞUL: schema.sql + migration-2026-07-saha-crm2.sql (listings_admin_insert)
--           + migration-2026-08-saha-paketi.sql çalışmış olmalı.
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
-- 1) ADAY KAYIT — public.prospects
-- ════════════════════════════════════════════════════════════════════
-- auth.users'a BAĞLI DEĞİL — kilidi açan şey tam olarak bu. Kişisel veri
-- (phone/email/note) YALNIZ admin tarafından okunur; hiçbir görünüme,
-- hiçbir anon RPC'ye sızmaz.
create table if not exists public.prospects (
  id           bigint generated by default as identity primary key,
  -- Davet linki jetonu. Mevcut üreteç iki kez: 12 karakter, karışan harf yok
  -- (0/O, 1/I/L). Telefonda okunacak kadar kısa, tahmin edilemeyecek kadar geniş.
  token        text not null unique default (public.gen_invite_code() || public.gen_invite_code()),
  name         text not null,
  role         text not null default '',   -- isveren | tedarikci | nakliyeci
  -- SAHA NOTU — yayınlanmaz. Vitrin ilanında firmanın numarası DEĞİL saha hattı görünür.
  phone        text not null default '',
  email        text not null default '',
  il           text not null default '',
  ilce         text not null default '',
  -- profiles'taki satıcı alanlarıyla birebir: sahiplenmede doğrudan kopyalanır.
  tesis_turu   text not null default '',
  hakkinda     text not null default '',
  malzemeler   text[] not null default '{}',
  note         text not null default '',   -- ziyaret / CRM notu
  status       text not null default 'taslak',
  -- RIZA: firma "evet" dedi mi, ne zaman, nasıl belgelendi.
  consent_at   timestamptz,
  consent_note text not null default '',
  claimed_by   uuid references public.profiles(id) on delete set null,
  claimed_at   timestamptz,
  created_by   uuid references public.profiles(id) on delete set null,
  created_at   timestamptz not null default now(),
  constraint prospects_status_chk check (status in ('taslak','yayinda','sahiplenildi','kapali')),
  constraint prospects_role_chk   check (role in ('','isveren','tedarikci','nakliyeci')),
  -- ── RIZA KAPISI ──────────────────────────────────────────────────
  -- OCAK-LISTESI.md'nin kuralı ("yayınlanmış uygulamada firma adına izinsiz
  -- ilan olmaz") artık bir belge tavsiyesi değil, VERİTABANI KISITI. Panelde
  -- düğmeyi gizlemek yetmez: rıza damgası yokken 'yayinda' satırı yazılamaz.
  constraint prospects_consent_chk check (status <> 'yayinda' or consent_at is not null)
);
create index if not exists prospects_status_idx  on public.prospects (status, created_at desc);
create index if not exists prospects_claimed_idx on public.prospects (claimed_by) where claimed_by is not null;

alter table public.prospects enable row level security;
drop policy if exists prospects_admin_all on public.prospects;
-- Okuma da yazma da YALNIZ admin. Kayıtsız/üye tarafın tek erişimi
-- prospect_by_token RPC'sidir ve o yalnız firma adı + il döndürür.
create policy prospects_admin_all on public.prospects
  for all using (public.is_admin()) with check (public.is_admin());
grant select, insert, update, delete on public.prospects to authenticated;


-- ════════════════════════════════════════════════════════════════════
-- 2) VİTRİN İLANI — listings.prospect_id
-- ════════════════════════════════════════════════════════════════════
-- Vitrin ilanı = owner_id NULL + prospect_id dolu. owner_id'nin null kalması
-- bilinçli: enforce_owner_snapshot bu satırlara dokunmuyor (schema.sql), accept_job
-- "Bu bir tanıtım ilanıdır — kabul edilemez" diyor ve istemcide isShowcase dalı
-- zaten kurulu. prospect_id o sahipsiz ilana KİMİN adına açıldığını bağlar.
alter table public.listings add column if not exists prospect_id bigint
  references public.prospects(id) on delete set null;
create index if not exists listings_prospect_idx on public.listings (prospect_id)
  where prospect_id is not null;


-- ── SAHA HATTI: app_config okuma politikası ──────────────────────────
-- Vitrin ilanında firmanın kendi numarası DEĞİL, YÜKLET saha hattı görünür.
-- Mevcut politika yalnız 'announcement' anahtarını serbest bırakıyordu; saha
-- hattı da herkese açık olmalı, yoksa sahipsiz ilanda aranacak numara HİÇ
-- görünmez (kayıtsız ziyaretçi zaten en değerli alıcı).
drop policy if exists app_config_read on public.app_config;
create policy app_config_read on public.app_config
  for select using (key in ('announcement','saha_hatti') or public.is_admin());


-- ════════════════════════════════════════════════════════════════════
-- 3) SÜRÜCÜ GUARD'I — SAHİPLENME İSTİSNASI
-- ════════════════════════════════════════════════════════════════════
-- schema.sql'deki sürümün BİREBİR üstüne yazılır; mevcut iki istisna (doğrudan
-- kabul + iptal) ve iç-trigger muafiyeti KORUNUR, sonuna üçüncüsü eklenir.
--
-- NEDEN ŞART: claim_prospect owner_id/owner_name/owner_* kolonlarını yazar ama
-- çağıran taraf ne ilan sahibi (owner_id null) ne admin. SECURITY DEFINER RLS'i
-- atlar, TRIGGER'I ATLAMAZ — bu istisna olmadan sahiplenme her seferinde
-- "Sürücü yalnız sefer alanlarını güncelleyebilir" ile patlardı. (Aynı tuzak
-- daha önce iş kabulünü kırmıştı: migration-2026-07-kabul-guard-fix.sql.)
create or replace function public.guard_driver_listing_update()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  allowed text[] := array['phase','status','cycle_stage','arrived_at','trips_done','delivery_proof','payment_received_at','payment_paid_at'];
begin
  -- İç-trigger muafiyeti: sync_offers_count gibi sistem trigger'larının yaptığı
  -- listings güncellemeleri (pg_trigger_depth 2+) kullanıcı kısıtına takılmasın.
  if pg_trigger_depth() > 1 then return new; end if;
  -- Sahip, admin ve doğrudan SQL (auth.uid() null) tam yetkili; yalnız sürücü kısıtlanır.
  if auth.uid() is null or auth.uid() = old.owner_id or public.is_admin() then
    return new;
  end if;
  -- DOĞRUDAN KABUL geçişi (aktif → eslesti): tek seferlik kendini-atama.
  if old.status = 'aktif' and new.status = 'eslesti'
     and old.accepted_by_id is null and new.accepted_by_id = auth.uid() then
    allowed := allowed || array['accepted_by_id','assigned_vehicle'];
  end if;
  -- İPTAL geçişi (eslesti → aktif, kabulün simetriği).
  if old.status = 'eslesti' and new.status = 'aktif'
     and old.accepted_by_id = auth.uid() and new.accepted_by_id is null then
    allowed := allowed || array['accepted_by_id','assigned_vehicle'];
  end if;
  -- YENİ — SAHİPLENME geçişi (saha aday kaydı): sahipsiz vitrin ilanı, firma
  -- kendi hesabını açınca ona devredilir. Güvenli, çünkü üç koşul birden aranır:
  --   • ilan gerçekten SAHİPSİZ (old.owner_id is null)
  --   • bir ADAY KAYDA bağlı (old.prospect_id is not null) — rastgele demo ilan değil
  --   • ve yalnız KENDİNE atanabilir (new.owner_id = auth.uid())
  -- Jetonu bilmeyen zaten claim_prospect'ten geçemez; bu istisna son kapıdır.
  if old.owner_id is null and old.prospect_id is not null
     and new.owner_id = auth.uid()
     and new.prospect_id is not distinct from old.prospect_id then
    allowed := allowed || array['owner_id','owner_name','owner_logo','owner_verified','owner_rating'];
  end if;
  if (to_jsonb(new) - allowed) is distinct from (to_jsonb(old) - allowed) then
    raise exception 'Sürücü yalnız sefer alanlarını güncelleyebilir';
  end if;
  return new;
end; $$;
drop trigger if exists on_listing_driver_guard on public.listings;
create trigger on_listing_driver_guard
  before update on public.listings
  for each row execute function public.guard_driver_listing_update();


-- ════════════════════════════════════════════════════════════════════
-- 4) YAYINLA / GERİ AL — admin
-- ════════════════════════════════════════════════════════════════════
-- Taslak adayın ilanları 'kapali' durur (panoda görünmez). Yayınlamak, aday
-- kaydı ile bağlı TÜM vitrin ilanlarını tek dokunuşta canlıya alır.
create or replace function public.publish_prospect(p_id bigint)
returns public.prospects language plpgsql security definer set search_path = public as $$
declare p public.prospects;
begin
  if not public.is_admin() then raise exception 'Yetki yok.'; end if;
  select * into p from public.prospects where id = p_id for update;
  if not found then raise exception 'Aday kayıt bulunamadı.'; end if;
  -- Kısıt zaten engelliyor; buradaki amaç panelde ANLAŞILIR hata göstermek.
  if p.consent_at is null then
    raise exception 'Rıza kaydı yok — firma "evet" demeden vitrin yayınlanamaz.';
  end if;
  update public.prospects set status = 'yayinda' where id = p_id returning * into p;
  update public.listings set status = 'aktif'
   where prospect_id = p_id and owner_id is null and status = 'kapali';
  return p;
end; $$;
revoke all on function public.publish_prospect(bigint) from public, anon;
grant execute on function public.publish_prospect(bigint) to authenticated;

create or replace function public.unpublish_prospect(p_id bigint)
returns public.prospects language plpgsql security definer set search_path = public as $$
declare p public.prospects;
begin
  if not public.is_admin() then raise exception 'Yetki yok.'; end if;
  select * into p from public.prospects where id = p_id for update;
  if not found then raise exception 'Aday kayıt bulunamadı.'; end if;
  -- Sahiplenilmiş adayın ilanları artık ÜYENİN malı; saha ekibi geri alamaz.
  if p.claimed_by is not null then
    raise exception 'Bu firma hesabını açtı — ilanları artık ona ait, buradan geri alınamaz.';
  end if;
  update public.prospects set status = 'kapali' where id = p_id returning * into p;
  update public.listings set status = 'kapali'
   where prospect_id = p_id and owner_id is null;
  return p;
end; $$;
revoke all on function public.unpublish_prospect(bigint) from public, anon;
grant execute on function public.unpublish_prospect(bigint) to authenticated;


-- ════════════════════════════════════════════════════════════════════
-- 5) DAVET LİNKİ — karşılama + sahiplenme
-- ════════════════════════════════════════════════════════════════════
-- Giriş ekranında "Akdağ Madencilik adına hesap açıyorsunuz" satırı için.
-- KAYITSIZ da çağırabilir (kişi henüz üye değil — bütün mesele bu), bu yüzden
-- YALNIZ firma adı + rol + il döner. phone/email/note/consent ASLA dönmez.
create or replace function public.prospect_by_token(p_token text)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
           'name', name, 'role', role, 'il', il, 'ilce', ilce,
           'claimed', claimed_by is not null
         )
    from public.prospects
   where coalesce(p_token,'') <> ''
     and upper(token) = upper(trim(p_token))
   limit 1;
$$;
revoke all on function public.prospect_by_token(text) from public;
grant execute on function public.prospect_by_token(text) to anon, authenticated;

-- Sahiplenme: aday kaydı + vitrin ilanları çağıranın hesabına geçer.
-- Döner: { ok, reason, name, role, listings }
create or replace function public.claim_prospect(p_token text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me      uuid := auth.uid();
  p       public.prospects;
  v_name  text;
  v_count int := 0;
begin
  if me is null then raise exception 'Giriş gerekli.'; end if;
  if coalesce(p_token,'') = '' then
    return jsonb_build_object('ok', false, 'reason', 'token_yok');
  end if;

  select * into p from public.prospects
   where upper(token) = upper(trim(p_token)) for update;
  if not found then return jsonb_build_object('ok', false, 'reason', 'bulunamadi'); end if;
  -- Tek kez sahiplenilir. Aynı kişi linke tekrar tıklarsa ok:true döner (akış
  -- sessizce devam etsin); BAŞKASI tıklarsa reddedilir.
  if p.claimed_by is not null then
    return jsonb_build_object('ok', p.claimed_by = me, 'reason', 'zaten_sahiplenildi', 'name', p.name);
  end if;
  if p.status = 'kapali' then
    return jsonb_build_object('ok', false, 'reason', 'kapali');
  end if;

  -- ── DEVİR KAPISI: yalnız TAZE hesap sahiplenebilir ────────────────
  -- Davet linki WhatsApp'ta iletilir ve gruplarda dolaşır. Bu kapı olmadan
  -- linki gören HERHANGİ bir üye firmanın kaydını üstüne alır: ilanları
  -- devralır ve kendi profil adı firma adıyla ezilir. Kendi ilanı olan ya
  -- da başka bir firmayı zaten sahiplenmiş hesap devir alamaz — gerçek
  -- alıcı taze hesap açar, kaybı yok.
  if exists (select 1 from public.listings where owner_id = me) then
    return jsonb_build_object('ok', false, 'reason', 'kurulu_hesap', 'name', p.name);
  end if;
  if exists (select 1 from public.prospects where claimed_by = me) then
    return jsonb_build_object('ok', false, 'reason', 'kurulu_hesap', 'name', p.name);
  end if;

  -- ── Profili doldur ────────────────────────────────────────────────
  -- Firma adı HER ZAMAN yazılır (aday kaydının bütün anlamı bu; Google'dan gelen
  -- kişisel ad yerine firma adı görünmeli). Diğer alanlar YALNIZ boşsa: üye
  -- kendisi bir şey girdiyse onun verisi üstündür.
  -- role: guard_profile_update yalnız '' ya da eski default 'isveren' iken
  -- değişime izin veriyor — aynı kuralı burada da uygula (guard sessizce geri
  -- almasın, niyet açık olsun).
  update public.profiles set
    name       = case when coalesce(p.name,'') <> '' then p.name else name end,
    phone      = case when coalesce(phone,'') = ''      then coalesce(p.phone,'')      else phone end,
    role       = case when coalesce(role,'') in ('','isveren')
                       and p.role in ('isveren','tedarikci','nakliyeci') then p.role else role end,
    sehir      = case when coalesce(sehir,'') = ''      then coalesce(p.il,'')         else sehir end,
    ilce       = case when coalesce(ilce,'') = ''       then coalesce(p.ilce,'')       else ilce end,
    tesis_turu = case when coalesce(tesis_turu,'') = '' then coalesce(p.tesis_turu,'') else tesis_turu end,
    hakkinda   = case when coalesce(hakkinda,'') = ''   then coalesce(p.hakkinda,'')   else hakkinda end,
    malzemeler = case when coalesce(array_length(malzemeler,1),0) = 0
                       then coalesce(p.malzemeler,'{}') else malzemeler end
  where id = me;

  select coalesce(name,'') into v_name from public.profiles where id = me;

  -- ── Vitrin ilanlarını devret ──────────────────────────────────────
  -- owner_verified/owner_rating ELLE yazılır: enforce_owner_snapshot yalnız
  -- BEFORE INSERT'te çalışır, UPDATE'te rozeti tazelemez.
  -- 'kapali' (henüz yayınlanmamış taslak) ilanlar da bu anda canlıya çıkar —
  -- firma artık gerçek sahibi, panoda durmasının önünde engel yok.
  update public.listings l set
    owner_id       = me,
    owner_name     = case when coalesce(p.name,'') <> '' then p.name else v_name end,
    owner_verified = coalesce((select verified from public.profiles where id = me), false),
    owner_rating   = coalesce((select rating   from public.profiles where id = me), 5.0),
    status         = case when l.status = 'kapali' then 'aktif' else l.status end
   where l.prospect_id = p.id and l.owner_id is null;
  get diagnostics v_count = row_count;

  update public.prospects
     set claimed_by = me, claimed_at = now(), status = 'sahiplenildi'
   where id = p.id;

  return jsonb_build_object('ok', true, 'name', p.name, 'role', p.role, 'listings', v_count);
end; $$;
revoke all on function public.claim_prospect(text) from public, anon;
grant execute on function public.claim_prospect(text) to authenticated;


-- ════════════════════════════════════════════════════════════════════
-- KONTROL — hepsi tek tek doğrulanabilir olmalı
-- ════════════════════════════════════════════════════════════════════
-- 1) tablo + RLS açık (1 satır, relrowsecurity = true):
select relname, relrowsecurity from pg_class where relname = 'prospects';
-- 1a) rıza kapısı dahil 3 kısıt:
select conname from pg_constraint where conrelid = 'public.prospects'::regclass
   and contype = 'c' order by conname;
-- 1b) tek politika (prospects_admin_all):
select policyname from pg_policies where tablename = 'prospects';
-- 2) vitrin bağı (1 satır):
select column_name from information_schema.columns
 where table_schema='public' and table_name='listings' and column_name='prospect_id';
-- 3) sürücü guard'ı ÜÇ istisnayı da taşıyor mu? (üçü de true)
select prosrc like '%accepted_by_id = auth.uid()%'   as kabul_var,
       prosrc like '%new.accepted_by_id is null%'    as iptal_var,
       prosrc like '%old.prospect_id is not null%'   as sahiplenme_var
  from pg_proc join pg_namespace n on n.oid = pronamespace
 where n.nspname='public' and proname='guard_driver_listing_update';
-- 4-5) RPC'ler (4 satır):
select proname from pg_proc join pg_namespace n on n.oid = pronamespace
 where n.nspname='public'
   and proname in ('publish_prospect','unpublish_prospect','prospect_by_token','claim_prospect')
 order by proname;
-- 6) RIZA KAPISI GERÇEKTEN TUTUYOR MU? Bu satır HATA vermeli
--    ("prospects_consent_chk" ihlali). Vermezse kapı çalışmıyor demektir.
--    (Kasıtlı hatalı sorgu — çalıştırıp hatayı gör, sonra geç.)
-- insert into public.prospects (name, role, status) values ('Kapı testi','tedarikci','yayinda');
